opentelemetry-collector:
  config:
    exporters:
      googlecloud:
    processors:
      resourcedetection/gcp:
        detectors: [env, gcp]
        timeout: 2s
        override: false
    service:
      pipelines:
        traces:
          exporters:
            - googlecloud
            - spanmetrics
          processors:
            - memory_limiter
            - batch
            - resourcedetection/gcp